version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: population_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  parse:
    image: python:3.11-slim
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python main.py parse"
    depends_on:
      - db

  stats:
    image: python:3.11-slim
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python main.py stats"
    depends_on:
      - db
      - parse  

volumes:
  postgres_data: